-- SQLite
UPDATE ClassAssignment
SET CLASS_ID = (SELECT MIN(CLASS_ID) FROM AdventureClass)
WHERE CLASS_ID BETWEEN 1 AND 10;

UPDATE Enrollment
SET CLASS_ID = (SELECT MIN(CLASS_ID) FROM AdventureClass)
WHERE CLASS_ID BETWEEN 1 AND 10;

