/*CREATE TABLE ADVENTURE_TRIP (
		 TRIP_ID DECIMAL(3),
		 TRIP_NAME VARCHAR(75),
		 START_LOCATION CHAR(50),
		 STATE_ CHAR(2),
		 DISTANCE INT,
		 MAX_GRP_SIZE INT,
		 TYPE_ CHAR(20),
		 SEASON CHAR(20),
);

INSERT INTO ADVENTURE_TRIP 
VALUES ('45','JAY PEAK', 'JAY', 'VT', '8', '8', 
'Hiking', 'Summer');

SELECT * FROM ADVENTURE_TRIP;*/

DELETE ADVENTURE_TRIP;